### ISSUE TITLE
How do I get MutationMaps for variant effect prediction?

### ISSUE THREAD

**Issue by sukritikumar4** [kipoi/kipoi-veff2#38]
I was looking to create mutation maps for the models under kipoi-veff2, would this be possible through this package?

**Comment by robertzeibich** [comment]
You would need to use kipoi-veff but this is a little tricky to install. If you install kipoi-veff, make sure you use kipoi=0.6.35 because with the current version, kipoi will not work. At least, I had my difficulties of getting it running with the current version. You also need to make sure that postprosessing is added in the model.yaml file otherwise an error is thrown.

**Comment by sukritikumar4** [comment]
Thank you so much @robertzeibich . I was facing the postprocessing error while trying to follow the example notebook given for mutation maps. Will try this method! This was very helpful.

**Comment by haimasree** [comment]
Hello! No sorry mutation map is not part of kipoi-veff2 and currently there is no plan to do so unfortunately. If you want to use mutationmap you must use kipoi-veff which at this point  is no longer being maintained. I will update the notebook to indicate this. Thanks for reporting. Feel free to write back if you have additional questions.
